---
title: "Worksheet 4"
subtitle: "Bayesian workflow and Stan"
author: "Robin Ryder & Joshua J Bon"
bibliography: ../assets/refs.bib
format: 
  html:
    html-math-method: katex
---

{{< include ../snippets/_data-download.qmd >}}

::: callout-tip
## Aims

Sampling from the posterior of a hierarchical model in `Stan`. Computing posterior predictive probabilities.
:::

::: {.callout-note collapse="true"}
## Resources

Chapter 6, @gelman2013bayesian
:::

::: {.callout-important collapse="true"}
## Data: `kidneycancerclean.csv`


Death rates for cancer of kidney/ureter for U.S. white males, 1980–1989[^1].

Data is separated in periods 1980--84 and 1985--89. We are interested in the columns `dc` and `dc.2`, which give the number of deaths from kidney cancer in each county, respectively in the years 1980--84 and 1985--89. The columns `pop` and `pop.2` are some measure of the population in the counties. We shall ignore the other columns.

`r download_data_buttom("kidneycancerclean.csv","kidneycancerclean")`

**Variable description**

1. `state`
2. `Location`
3. `fips`
4. `dc`: Deaths from kidney cancer 1980--84
5. `dcV`
6. `pop`: County population 1980--84
7. `popV`
8. `aadc`
9. `aadcV`
10. `dcC`
11. `dcCV`
12. `good`
13. `dc.2`: Deaths from kidney cancer 1985--89
14. `dcV.2`
15. `pop.2`: County population 1985--89
16. `popV.2`
17. `aadc.2`
18. `aadcV.2`
19. `dcC.2`
20. `dcCV.2`
21. `good.2`

:::

[^1]: Data from Chapter 2.7 @gelman2013bayesian

## Activity 1: Getting started

Download and import the kidney cancer data into `R`. 

Think about these data: which aspects are striking and will need to be particularly kept in mind when checking the model fit?

```{r data}
#| code-summary: "Starting code"
#| echo: true
#| code-fold: true
#| eval: false

library(readr)
library(ggplot2)

kidney <- read_csv("/path/to/kidneycancerclean.csv", skip = 4, col_types = cols(col_skip(), col_guess()))
  # Discards the first 4 rows and first column.

kidney <- kidney %>% 
  mutate(total_deaths = dc + dc.2) %>% # 1980-1989
  mutate(population = (pop+pop.2)/2) %>% # average in 1980-1989
  mutate(theta_hat = total_deaths/(10*population)) # estimate of annual death rate (/10 to average over 10 years)

```


## Activity 2: Model with global average rate

Suppose all county death counts $y_i$ are identically distributed with joint rate parameter $\theta$. That is

$$y_i \mid n_i, \theta \sim \text{Poisson}(10 n_i \theta)$$
where $n_i$ is the population of the county.

1. Is this model reasonable?
2. Propose a Frequentist estimate
3. Code the IID model in `Stan` and use the `rstan` package for inference
4. Check convergence and sample size
5. Compare the Frequentist and Bayesian estimates

## Activity 3: Model with local average rates

Suppose all observations are independent now with individual rates $\theta_i$.

1. Is this model reasonable?
2. Propose a Frequentist estimate and visualize it.
3. Code the independence model in `Stan` and use the `rstan` package for inference
4. Check convergence and sample size
5. Compare the Frequentist and Bayesian estimates

## Activity 4: Hierarchical model

1. Implement a Bayesian hierarchical model in `Stan` and use the `rstan` package for inference.
2. Follow a Bayesian workflow (iterating as need):
    - Build Bayesian model
    - Compute posterior
    - Evaluate posterior

3. Simulate synthetic data and perform the relevant posterior predictive checks.
4. Compare uncertainty of estimates to independence model



